[#13] 상품 엔티티 추가
f-lab-edu/ready-auction pull request #16
Opened 2024-07-26 22:31 UTC by JIWON27

### 상품 엔티티 추가
- id
- 등록자 (User)
    - User : 상품 = 1 : N 관계
- 이름
- 설명
- 상품 이미지
- 경매 시작일
- 경매 종료일
- 경매 시작가
- 상품 상태
    - PENDING : 대기
    - ACTIVE : 진행중
    - DONE : 종료
- 생성자와 상품 수정 메서드

2024-07-27 12:03 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 한번 부탁드려요 ~
이전꺼랑 같이 푸시 한번 해주시면 좋을 것 같습니다

2024-07-27 12:03 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Status.java
> +@Getter
getter는 왜 붙인걸까요 ?

2024-07-27 12:03 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +	public void updateProductInfo(String name, String description, List<String> imagePaths, ZonedDateTime startDate,
생성자가 제일 위로 올라오는게 좋을 것 같아요 ~

2024-07-27 12:03 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +	private ZonedDateTime startDate;
혹시 ZonedDateTime을 쓰신 이유가 있을까요 ? 보통은 LocalDateTime을 써서요!

2024-07-27 12:03 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +@Entity
`@Table`이나 `@Column` 어노테이션도 사용하시면 좋을 것 같아요 ~
JPA가 만들어줘서 의미없다고 느끼실수도 있는데, 실무에선 JPA로 테이블 자동생성을 하지 않아서 수동으로 만든 테이블과 맵핑하기 때문에 명시적으로 적어주는게 좋아요

2024-07-27 12:43 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Status.java
> +@Getter
앗 자꾸 습관적으로 @Getter를 붙이는거같습니다.
생각하고 사용하도록 하겠습니다 ㅠㅠ

2024-07-27 12:43 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +	public void updateProductInfo(String name, String description, List<String> imagePaths, ZonedDateTime startDate,
넵 수정하도록 하겠습니다!

2024-07-28 02:17 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +	private ZonedDateTime startDate;
ZonedDateTime는 시차 개념까지 함꼐 들어있어서 사용했는데 지금 프로젝트에서는 LocalDateTime이 맞는거같습니다.
수정하도록 하겠습니다!

2024-07-28 02:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +@Entity
아 넵!! 추가하도록 하겠습니다!

2024-07-28 13:18 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Status.java
> +@Getter
`@getter` 요렇게 써주세요! 그냥 어노테이션 붙이면 사람 태그돼요 ㅋㅋ

2024-07-28 13:23 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Status.java
> +@Getter
헉!! 수정했습니다!! 감사합니다!!!!

2024-07-28 13:34 UTC, f-lab-moony approved these changes
고생 많으셨습니다~
머지 해 둘게요!

2024-07-28 13:35 UTC, merged