경매 상품 CRUD - 중간점검
f-lab-edu/ready-auction pull request #19
Opened 2024-08-05 15:39 UTC by JIWON27

### 경매 상품 CRUD - 중간점검
-  `@LoginUser` 애노테이션 생성
    - 현재 로그인된 사용자 정보를 세션에서 가져오도록 함.

2024-08-09 08:28 UTC, f-lab-moony requested changes
고생많으셨습니다!
저번에 멘토링시간에 다 피드백 한줄알고 깜빡했네요..!
피드백 확인 후 리뷰 재요청 해주세요!

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +		@LoginUser User user,
`@Authentication` 쓰면 되지 않나요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/config/WebConfig.java
> +	private final LoginUserArgumentResolver loginUserArgumentResolver;
리졸버 추가해보는거 좋네요 👍

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	@GetMapping("/api/v1/products/{id}")
약간 개취긴한데, 컨트롤러의 메인 패스 (여기선 /api/v1/products/) 는 클래스에 지정해보는건 어떨까요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +		@RequestPart(name = "Images") List<MultipartFile> files) {
파일도 Request 안에 받을 수 있지 않나요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductDeleteResponse.java
> +	public ProductDeleteResponse from(Long id) {
요건 static으로 만들어보는게 어떨까요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +	public ProductFindResponse(UserResponse userResponse, List<ImageResponse> imagePath, String productName,
줄바꿈이 제멋대로인거같은데, Intellij에 컨벤션 등록하고 save action 추가하는거 추천드려요 ~

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +	public ProductFindResponse(UserResponse userResponse, List<ImageResponse> imagePath, String productName,
요거 `@Builder` 써보는건 어떨까요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductUpdateResponse.java
> +	private Long id; // 업데이트 성공한 상품의 ID를 반환
요런 주석은 왠만하면 안남기는게 좋아요!

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +@Table(name = "Product_Image")
테이블명은 소문자로 해주세요 ~

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +	@Column(name = "savedName", nullable = false)
db 컬럼명은 snake_case로 작성해주세요 ~

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/resolver/LoginUserArgumentResolver.java
> +			User user = userService.getCurrentLoginUser();
쿼리를 해서 가져오는군요 ?

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	// 운영 서버일때는 S3 이런걸로 할 수 있도록 프로파일링 하기
요렇게 히스토리가 필요한 주석은 javadoc 으로 달아주시면 좋아요 ~ `/* */` 요기안에!

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			try {
try-catch가 중간에 있으면 뎁스가 많이들어가서 가독성이 떨어져요. 메서드로 분리하면 좋을 것 같아요

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	@Override
서비스에는 `@Transactional` 을 붙여주세요 ~

2024-08-09 08:28 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			.map(productImage -> new ImageResponse(
stream API를 사용하면, 선언형 프로그래밍으로 가독성을 높일 수 있다는 장점이 있는데요, 요렇게 하면 `어떻게` 하는지가 드러나기떄문에 `무엇을` 하는지를 드러낼 수 있도록 메서드 분리를 해보면 좋을 것 같아요

2024-08-10 04:25 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +		@LoginUser User user,
`@Authentication `애노테이션이 `@Authenticationpricipal` 말씀하시는건가여?
저는 일반 세션 로그인을 해서 뷰 리졸버를 통해 세션에서 유저를 가져오도록 했습니다!

2024-08-10 04:25 UTC, JIWON27 commented on src/main/java/com/example/readyauction/config/WebConfig.java
> +	private final LoginUserArgumentResolver loginUserArgumentResolver;
감사합니다!!

2024-08-10 04:26 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	@GetMapping("/api/v1/products/{id}")
아 넵! 클래스에 지정하도록 하겠습니다

2024-08-10 04:44 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	// 운영 서버일때는 S3 이런걸로 할 수 있도록 프로파일링 하기
아 넵 히스토리가 필요한 부분은 javadoc으로 달겠습니다.

2024-08-10 04:44 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			try {
넵 가독성 신경써서 작성하겠습니다.

2024-08-10 04:44 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	@Override
아 넵!! 감사합니다

2024-08-10 04:44 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			.map(productImage -> new ImageResponse(
넵 피드백 반영해서 코드 수정하겠씁니다.

2024-08-10 05:00 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +		@RequestPart(name = "Images") List<MultipartFile> files) {
하나의 DTO에 Multipart파일까지 다 받으라는 말씀이 맞을까요?!
제가 알기로는 하나의 DTO에 다 넣으면 일반 JSON 데이터들도 Multipart/form-data 형식으로 보내야한다는 단점이 있는걸로 알고있습니다. `@RequestPart`로 하면 JSON데이터들은 applicatin/json으로, 이미지는 Multipart/form-data로 보낼 수 있어서 사용했습니다!

2024-08-10 05:05 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductDeleteResponse.java
> +	public ProductDeleteResponse from(Long id) {
아 넵! static 메소드로 만들겠습니다! static 메소드와 지금과 같은 메소드로 할 시 혹시 어떤 차이가 있는지 알려주실 수 있으신가요?!
메모리에 올라가는 방식 차이가 아닌 기능적인 차이가 궁금합니다!

2024-08-10 06:06 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +	public ProductFindResponse(UserResponse userResponse, List<ImageResponse> imagePath, String productName,
아 넵!! 적용 다시 확인하겠습니다

2024-08-10 06:07 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductUpdateResponse.java
> +	private Long id; // 업데이트 성공한 상품의 ID를 반환
아 넵! 삭제하도록 하겠습니다.

2024-08-10 06:07 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +@Table(name = "Product_Image")
넵 수정하겠습니다.

2024-08-10 06:07 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +	@Column(name = "savedName", nullable = false)
넵..!! 감사합니다

2024-08-10 06:10 UTC, JIWON27 commented on src/main/java/com/example/readyauction/resolver/LoginUserArgumentResolver.java
> +			User user = userService.getCurrentLoginUser();
혹시 어떤 말씀이신지 설명해주실 수 있으실까요..??
 userService의 getCurrentLoginUser() 메서드는 loginService에서 현재 로그인한 userId를 가져오고, userId를 사용해서 User를 찾아서 반환해주는 메서드 입니다!

2024-08-10 06:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +	public ProductFindResponse(UserResponse userResponse, List<ImageResponse> imagePath, String productName,
다른 부분에서는 `@Builder`를 사용안했는데  생성자쪽은 모두 `@Builder`를 붙여주는게 나은가요?

2024-08-10 11:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +		@RequestPart(name = "Images") List<MultipartFile> files) {
아, 이건 그냥 파일을 그대로 받는거군요. 저는 클라이언트에서 파일을 한번 디코딩해서 줬어서 그냥 json으로 다 받은 기억이 있는데, 전처리가 없으면 말씀하신대로 되겠네요!

2024-08-10 11:44 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductDeleteResponse.java
> +	public ProductDeleteResponse from(Long id) {
네 맞습니다~

성능적으론 별 차이 없어요. 근데 보통 생성자에는 로직을 넣지 않는다는 불문율이 있기도 하고, 생성자가 다른 패키지에 의존성을 가지게 되면 결합도가 높아지기 때문에 생성자는 보통 범용적으로 쓰는 타입들 ( primitive, LocalDate 같은 애들 ) 로 구성하는게 좋아요 ~

2024-08-10 11:44 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/resolver/LoginUserArgumentResolver.java
> +			User user = userService.getCurrentLoginUser();
세션에서 찾아오는건가요 ? 직접 만드신 메서드인줄알았어요!

2024-08-10 18:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/FileService.java
> +	//List<ProductImage> uploadImage(String userId, MultipartFile file);
이 부분은 API로 넘겨줄때부터 List 타입이어서 단일 파일 처리하는게 필요없다고 생각이 들어서 삭제했습니다.

2024-08-10 18:15 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	/* @Override
이 부분도 단일 파일을 처리하는 메서드를 삭제해서 일단은 주석처리했습니다.

2024-08-10 18:16 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			imageSave(productImages, file, productImage);
코멘트 달아주신 피드백처럼 stream을 사용하는 목적에 맞도록 코드 수정했습니다!

2024-08-10 18:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			.map(ImageResponse::from)
코멘트 달아주신 피드백처럼 stream을 사용하는 목적에 맞도록 코드 수정했습니다!

2024-08-10 18:21 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductResponse.java
CUD는 공통적으로 Id를 반환해주도록 할려고해서 공통 ResponseDTO를 만들었고 개별로 만들어져있었던 CUD ResponseDTO들은 삭제했습니다!

2024-08-11 10:22 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/FileService.java
> +	//List<ProductImage> uploadImage(String userId, MultipartFile file);
단건 메서드가 필요 없는지 의견을 듣고싶으시다는 말씀이실까요 ? 저도 쓰는데가 없다면 딱히 만들필요 없다고 생각합니다

2024-08-11 10:23 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			imageSave(productImages, file, productImage);
약간 사소한건데, 메서드 이름을 지을때는 동사가 앞에 나오는게 자연스러워요! 다른건 그렇게 하셨는데 요건 순서가 좀 달라서 어색해보이네요

2024-08-11 11:05 UTC, f-lab-moony requested changes
고생하셨습니다 ~
피드백 확인 부탁드려요!

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +				throw new DeleteImageFailException(e);
이거 여기서 실패하고 튕겨내면 이 파일은 언제 삭제될 수 있는걸까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	public void deleteImagesDB(Product product) {
추상화가 너무 디테일하게 된 것 같아요 delete만 있어도 되지 않을까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			productImages.add(productImage);
add를 굳이 여기서 할 이유가 있었을까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +		String SavedImageFullPath = createSavedImageFullPath(userId, savedFileName);
변수명은 lowerCamelCase로 작성해주세요 ~

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +		StringBuilder fullDirPath = new StringBuilder()
줄임말은 지양해주세요 ~

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +		product.mappingUser(user);
요건 뭘까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	public List<ProductImage> uploadImages(String userId, List<MultipartFile> files) {
얘는 뭔가 파일 업로드만 하려고 만드신 것 같은데 DB 작업에 대한 책임은 왜 지고 있는걸까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +			productImages.forEach(productImage -> productImage.mappingProduct(product));
프로덕트 먼저 만드시고 image 저장할때 넘겨주면 이걸 안해도 되지 않을까요 ?

2024-08-11 11:05 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +		product.updateProductInfo(productUpdateRequest); // 필드들을 따로 넘기기에는 넘 길어서 그냥 DTO를 넘김.
도메인에서 dto는 참조 안하게 해주세요 이 구조는 dto를 변경하면 도메인에 영향이 가고, 패키지가 커플링 될 것 같아요

2024-08-12 10:52 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/FileService.java
> +	//List<ProductImage> uploadImage(String userId, MultipartFile file);
넵 맞습니다! 감사합니다!

2024-08-12 10:53 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			imageSave(productImages, file, productImage);
아 수정하도록 하겠습니다~!

2024-08-12 12:19 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +		String SavedImageFullPath = createSavedImageFullPath(userId, savedFileName);
넵 수정하겠습니다.

2024-08-12 12:20 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +		StringBuilder fullDirPath = new StringBuilder()
아 자꾸 줄임말 쓰네요 ㅠㅠ 신경써서 개발하겠습니다!

2024-08-12 12:27 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +			productImages.add(productImage);
확인해보니 imageSave 메서드에서 add를 하는 것이 메서드의 역할과 맞지 않는 것 같아서, add 기능을 uploadImages에서 처리하도록 수정했습니다.

2024-08-12 14:38 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	public void deleteImagesDB(Product product) {
아 ! delete 메서드로 통합하겠습니다! 감사합니다.

2024-08-12 14:39 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +		product.mappingUser(user);
연관관계 매핑하는 부분인데.. 멘토링 시간대 피드백 주신 내용 생각해서 수정하겠습니다!

2024-08-12 14:39 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	public List<ProductImage> uploadImages(String userId, List<MultipartFile> files) {
책임 분리하도록 하겠습니다!

2024-08-12 14:39 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +			productImages.forEach(productImage -> productImage.mappingProduct(product));
피드백 반영하겠습니다!

2024-08-12 14:39 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +		product.updateProductInfo(productUpdateRequest); // 필드들을 따로 넘기기에는 넘 길어서 그냥 DTO를 넘김.
앗 넵!! 자꾸 놓치는 것 같습니다ㅠㅠ 감사합니다! 피드백 반영하겠습니다.

2024-08-12 14:45 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +				throw new DeleteImageFailException(e);
놓친 부분인거같습니다. 고민하고 추가하도록 하겠습니다!

2024-08-13 16:31 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +    private String userId;
user 테이블과 연관관계를 끊고 userId를 넘겨주도록 수정했습니다.

2024-08-13 16:34 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +    private Long productId;
ProductImage도 Product와 연관관계를 끊고 ProductId를 가지고 있도록 수정했습니다.
연관관계를 맺을까 고민했는데 없는게 더 간단하다고 생각이 들어서 수정했습니다.

2024-08-13 16:34 UTC, JIWON27 commented on src/main/java/com/example/readyauction/exception/product/UnauthorizedProductAccessException.java
> +public class UnauthorizedProductAccessException extends RuntimeException {
경매 상품이 내가 등록한 상품이 아니거나, 경매 상품 상태가 대기중이 아닐때 접근하면 발생하는 예외입니다.

2024-08-13 16:35 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
LocalFileService에 구현되어있던 DB 작업들은 모두 제거했습니다.

2024-08-13 16:36 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/FileService.java
> +    void delete(List<ImageResponse> imageResponses);
원래 deleteImagesLocal, deleteImagesDB로 존재하던 메서드들을 delete라는 메서드로 통합해 구체적이었던 추상화를 없앴습니다.

2024-08-13 16:37 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +    private void checkProductAccessPermission(Long id, String userId) {
경매 상품에 접근이 가능한지 검증하는 메서드입니다.

2024-08-13 16:37 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +        Product product = productSaveRequest.toEntity(userId);
user 테이블과 연관관계를 끊어서 userId를 넘겨주었습니다.

2024-08-13 16:38 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +            for (ProductImage productImage : loadProductImages) {
이미지 수정시 기존에 있던 이미지들은 삭제하고 다시 재업로드 하도록 했습니다.

2024-08-13 16:50 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +                throw new DeleteImageFailException(e);
삭제 실패한 이미지 처리에 대해서는 아직 고민하고있습니다..

2024-08-13 16:51 UTC, JIWON27 commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
ProductService 테스트 코드입니다.

2024-08-13 16:51 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
>      public ProductResponse delete(String userId, Long productId) {
상품 삭제시 관련된 이미지들도 삭제할 수 있도록 추가했습니다.

2024-08-13 17:03 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/apiException/ApiExceptionController.java
>  public class ApiExceptionController {
Product API `@ExceptionHandler` 추가했습니다.

2024-08-14 15:31 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~

요번 피드백도 처리하고 진행해보시죠!

2024-08-14 15:31 UTC, f-lab-moony commented on .gitignore
> +Images/*
.gradle이랑 build 폴더가 같이 올라오는거같은데 요것도 잡아주세요!

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        ProductResponse productSaveResponse = productService.enroll(user.getUserId(), productSaveRequest, files);
요런거 변수로 한번 받을 필요 없지 않을까요 ?

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/request/product/ProductSaveRequest.java
> +    public Product toEntity(String userId) {
이 userId도 클라이언트에서 받아야되지 않을까요 ?
클라이언트도 유저 아이디를 알고 있을건데 굳이 로그인한 유저 정보로 찾을 이유가 없을 것 같아요
만약 현재 세션으로 로그인한 유저만 가능한 기능이라면 추가 유효성검사를 하는게 맞지 않을까 싶네요!

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/request/product/ProductUpdateRequest.java
> +		LocalDateTime closeDate,
줄바꿈이 좀 이상한거같아요 ?

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +    public ProductFindResponse from(Product product, List<ImageResponse> imageResponses) {
요것도 static으로 하는게 맞을 것 같아요 ~

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductResponse.java
👍 
근데 공통적으로 id 반환이면 DTO 필요 없지않나요 ?

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +    public void updateProductInfo(String productName, String description, LocalDateTime startDate,
👍

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +@Table(name = "product_Image")
db의 오브젝트들은 다 lower snake case로 작성해주세요~

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +    private Long productId;
어떤 면에서 더 간단하다고 생각하셨는지 정리해주시면 더 좋을 것 같아요!

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/exception/file/CreateDirectoryFailException.java
> +
요기도 줄바꿈이 약간 이상하네요!

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/exception/file/DeleteImageFailException.java
> +	public DeleteImageFailException(Throwable e) {
근데 인덴트가 엄청 기네요 ? 보통 4 정도로 쓰는데, 지금 8로 설정돼있나요 ?

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductImageRepository.java
> +public interface ProductImageRepository extends JpaRepository<ProductImage, Long> {
`@Repository` 가 빠진 것 같아요 ~

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	*/
인덴트가 왜 얘만 더 들어가있지 ..? 설정을 중간에 바꾸셨나요 ?

2024-08-14 15:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +        return imageResponses;
요것도 변수로 뺄 필요 없을 것 같아요!

2024-08-14 15:31 UTC, f-lab-moony commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +    Product product = Product.builder()
테스트에 사용되는 데이터들은 각 테스트에서 만들어주는게 좋을 것 같아요
각각의 테스트는 격리되어 서로간에 영향을 안주는게 중요해요
보통 어플리케이션 코드는 재사용성이 중요하지만, 테스트는 재사용성보다는 가독성이 훨씬 중요하기때문에 어디서 어떤 값을 가지고 만들어지는지가 한 테스트 내에서 드러나야 테스트의 의도가 파악이 됩니다

변수를 재사용하기보단 fixture를 찾아보시고 그렇게 적용해서 쓰는 방법을 추천드립니다 ~ groovy에선 fixture 만들기도 쉬워서 spock의 장점이 또 드러날 수 있겠네요

2024-08-14 15:31 UTC, f-lab-moony commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +        List<MultipartFile> images = new ArrayList<>()
groovy는
````
def images = [ mockMultipartFile1, mockMultipartFile2 ]
````
이렇게 쓸 수 있어요 ~

2024-08-14 15:31 UTC, f-lab-moony commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +        List<MultipartFile> images = new ArrayList<>()// 이 부분은 어떻게 해야하는거지
뭐가 궁금하신거죠

2024-08-14 15:31 UTC, f-lab-moony commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +        fileService.loadImages(productImages) >> _
이건 뭐죠 ? 리턴값이 없다는걸 표현하고 싶으신건가요 ?

2024-08-15 01:07 UTC, JIWON27 commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +        List<MultipartFile> images = new ArrayList<>()// 이 부분은 어떻게 해야하는거지
앗 의미없는 주석입니다!!! ㅎㅎ...

2024-08-15 01:09 UTC, JIWON27 commented on .gitignore
> +Images/*
넵 .gitignore가 적용이 안된거같습니다 ,, 확인해보겠습니다

2024-08-15 01:12 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/request/product/ProductUpdateRequest.java
> +		LocalDateTime closeDate,
앗 넵,, 수정하겠습니다!

2024-08-15 01:55 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +    private Long productId;
멘토링 때 말씀해주신 것처럼 연관관계를 맺으면 쿼리도 잘 안보이고, JPA에서 발생할 수 있는 문제점을 고려하는 것보다 
productId로 필요한 작업을 하는 코드를 추가해주는게 더 간단하다는 생각이 들어서 끊었습니다.

2024-08-15 01:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        ProductResponse productSaveResponse = productService.enroll(user.getUserId(), productSaveRequest, files);
아 넵 User를 받도록 수정하겠습니다!

2024-08-15 02:06 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductFindResponse.java
> +    public ProductFindResponse from(Product product, List<ImageResponse> imageResponses) {
앗 넵 !!

2024-08-15 02:08 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/ProductImage.java
> +@Table(name = "product_Image")
넵! 수정하도록 하겠습니다.

2024-08-15 02:09 UTC, JIWON27 commented on src/main/java/com/example/readyauction/exception/file/CreateDirectoryFailException.java
> +
앗 넵 줄바꿈 신경쓰도록 하겠습니다!! ㅜㅜ

2024-08-15 02:11 UTC, JIWON27 commented on src/main/java/com/example/readyauction/exception/file/DeleteImageFailException.java
> +	public DeleteImageFailException(Throwable e) {
4로 설정되어있는데 이 부분이 작성하면서 조금 인덴트가 길게된거같습니다! 수정했습니다.

2024-08-15 02:11 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductImageRepository.java
> +public interface ProductImageRepository extends JpaRepository<ProductImage, Long> {
앗 추가했습니다.......

2024-08-15 02:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +	*/
앗 아뇨.. 인덴트 신경쓰도록 하겠습니다!

2024-08-15 02:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +        return imageResponses;
아 넵 바로 return하도록 하겠습니다!

2024-08-15 03:28 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/request/product/ProductSaveRequest.java
> +    public Product toEntity(String userId) {
아 생각도 못했습니다!! userId도 클라이언트에 받도록 하도록 수정하고 추가 유효성 검사도 추가하겠습니다.!

2024-08-15 13:15 UTC, JIWON27 commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
> +        fileService.loadImages(productImages) >> _
아 반환값을 고민하다가 _ 한걸 그대로 올렸습니다,, 테스트 코드는 다시 수정하고 올리겠습니다.

2024-08-15 13:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/apiException/ApiExceptionController.java
> +    public ErrorResponse productEnroll(UnauthorizedEnrollException e) {
상품 등록에서 사용자 유효성 검증 실패를 처리하는 `@ExceptionHander`추가했습니다.

2024-08-15 13:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +    private final ProductFacade productFacade;
ProductFacde를 사용하도록 수정했습니다.

2024-08-15 13:19 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/request/product/ProductSaveRequest.java
> +    private String userId;
클라이언트에서 userId도 받을 수 있게 추가했습니다!

2024-08-15 13:19 UTC, JIWON27 commented on src/main/java/com/example/readyauction/exception/product/UnauthorizedEnrollException.java
> +public class UnauthorizedEnrollException extends RuntimeException {
상품 등록에서 사용자 유효성 검증 실패 예외입니다.

2024-08-15 13:20 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/file/LocalFileService.java
> +    public List<ProductImage> updateImages(User user, Product product, List<ProductImage> productImages, List<MultipartFile> images) {
로컬 이미지를 업데이트 하는 메서드 추가했습니다.

2024-08-15 13:22 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +public class ProductFacade {
ProductService : 상품에 대한 처리
ProductImageService : 상품 이미지에 대한 처리(DB)
FileService : 상품 이미지에 대한 처리(로컬, S3(예정))
를 참조하는 ProductFacade서비스입니다.

2024-08-15 13:23 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductImageService.java
> +public class ProductImageService {
ProductImage를 처리하는 서비스입니다.

2024-08-15 13:23 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
>  public class ProductService {
FileService, ProductImageService에 관한 작업은 모두 삭제했습니다.
Product에 대한 작업만 가지도록 했습니다.

2024-08-19 20:03 UTC, JIWON27 commented on src/test/java/com/example/readyauction/service/product/ProductServiceTest.groovy
수정한 ProductService 테스트 코드입니다.

2024-08-19 20:03 UTC, JIWON27 commented on src/test/java/com/example/readyauction/service/product/ProductFacadeTest.groovy
ProductFacade 서비스 테스트 코드입니다.

2024-08-21 00:56 UTC, f-lab-moony approved these changes
고생 많으셨습니다! 이 PR은 이제 머지할게요!

2024-08-21 00:56 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +    public ProductResponse enroll(User user, ProductSaveRequest productSaveRequest, List<MultipartFile> images) {
요긴 `@Transactional` 이 없어도 되나요 ?

2024-08-21 00:56 UTC, merged