[#24] 경매 상품 페이징, 정렬 기능 추가
f-lab-edu/ready-auction pull request #25
Opened 2024-08-31 06:48 UTC by JIWON27

### 경매 상품 페이징, 정렬 기능 추가 
- 커서 페이징 
- 디폴트 정렬 : 최신순
- 경매 시작일이 빠른 순 정렬 기능 추가
- 정렬 조건들은 나중에 추가 가능

2024-08-31 06:48 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	private static final int DEFAULT_SIZE = 6;
PageSize는 디폴트값으로 6으로 했습니다

2024-08-31 06:49 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	public ProductCursorResponse findAll(
cursorId, sortedBy(정렬조건) 추가했습니다.

2024-08-31 06:51 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductCursorResponse.java
> +public class ProductCursorResponse {
ProductFindResponse와 nextCursorId, 다음이 있는지 없는지도 알려주는 hasNext를 반환해줍니다.
근데 만약 다음이 없으면 nextCursorId를 -1로 반환해주는데, -1인지 아닌지로도 다음이 있는지 없는지를 판단할 수 있는데 hasNext가 굳이 필요한가? 라는 생각이 들어서 삭제할지 고민입니다.

2024-08-31 06:52 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByOrderByIdDesc(Pageable pageable);
가장 최초 조회 시 cursorId가 없으니까 최신순 조회하도록 하는 기능입니다.

2024-08-31 06:52 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByIdLessThanOrderByIdDesc(Long cursorId, Pageable pageable);
cursorId가 있을 때, 최신순 조회하도록 해주는 기능입니다.

2024-08-31 07:55 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	private static final int DEFAULT_SIZE = 6;
디폴트로 PageSize는 6으로 했습니다.

2024-08-31 07:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +	public ProductCursorResponse findAll(
cursorId랑 sortedBy를 추가한 조회 기능입니다.

2024-08-31 07:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductCursorResponse.java
> +public class ProductCursorResponse {
ProductFindResponse와 nextCursorId, 다음이 있는지 없는지도 알려주는 hasNext를 반환해주도록 했습니다.
근데 만약 다음이 없으면 nextCursorId를 -1로 반환해주는데, -1인지 아닌지로도 다음 조회할 상품이이 있는지 없는지를 판단할 수 있는데 hasNext가 굳이 필요한가? 라는 생각이 들어서 삭제할지 고민입니다..

2024-08-31 07:57 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByOrderByIdDesc(Pageable pageable);
아무 조건없이 최초 조회시 (cursorId == null) 최신순으로 pageSize만큼 불러오도록했습니다.

2024-08-31 07:58 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByIdLessThanOrderByIdDesc(Long cursorId, Pageable pageable);
cursorId 기준으로 , pageSize만큼 최신순으로 불러오도록했습니다.

2024-08-31 07:59 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByOrderByStartDateAsc(Pageable pageable);
cursorId 없이 sortedBy 정렬 기준으로 pageSize 만큼만 가져오는 했습니다.

2024-08-31 07:59 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepository.java
> +	List<Product> findAllByIdLessThanOrderByStartDateAsc(Long cursorId, Pageable pageable);
cursorId와 sortedBy 정렬 기준으로 상품을 가져오도록 했습니다.

2024-08-31 08:06 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +		Long nextCursorId = hasNext ? products.get(products.size() - 1).getId() : -1;
cursorId가 DB에서 id(pk)이면 nextCursorId를 -1해서 구할 수 있는데.. startDate 처럼 정렬 조건이 들어가는 순간 cursorId 기준이 애매해져서 고민하고있습니다..

2024-08-31 08:09 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProducts(Long cursorId, String sortedBy, Pageable pageable) {
여기는 일단은 조건문을 사용했는데 동적 쿼리로 수정할 생각입니다.

2024-08-31 08:09 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProductByCursorIdAndSortedBy(Long cursorId, String sortedBy, Pageable pageable) {
cursorId, sortedBy 둘다 값이 들어있을때 조회하는 기능입니다.

2024-08-31 08:10 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProductBySortedBy(String sortedBy, Pageable pageable) {
cursorId없이 sortedBy로만 조회하는 기능을 수행합니다.

2024-08-31 08:11 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	public List<Product> findAll(Long cursorId, String sortedBy, int size) {
cursorId, sortedBy로 상품 조회를 담당하는 부분입니다.

2024-08-31 08:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +	public ProductCursorResponse findAll(Long cursorId, String sortedBy, int size) {
ProductFacde 부분에서 cursorId, sortedBy 기준으로 상품을 조회하는 기능을 담당합니다.

2024-08-31 08:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	public List<Product> findAll(Long cursorId, String sortedBy, int size) {
cursorId, sortedBy로 상품 조회를 담당하는 부분입니다.

2024-08-31 15:00 UTC, f-lab-moony reviewed
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-08-31 15:00 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +			.map(product -> {
stream api를 사용하면 선언형으로 만들 수 있어서 가독성을 향상시킨다는 메리트가 있는데요, stream api를 사용할 땐 요렇게 어떻게 하는지를 드러내기보단 메서드 분리를 통해 무엇을 하는지에 집중할 수 있도록 만들어주시면 좋을 것 같아요 ~

2024-08-31 15:00 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +		Long nextCursorId = hasNext ? products.get(products.size() - 1).getId() : -1;
스레드에도 남기긴 했는데 요거 말씀이 이해가 안돼요! 조건이 무슨상관일까요 ?

2024-08-31 15:00 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProductByCursorIdAndSortedBy(Long cursorId, String sortedBy, Pageable pageable) {
위에 말씀하신거처럼 동적쿼리로 바꿀때 QueryDSL 사용하시면 많이 깔끔해질 것 같네요 ~
그리고 정렬조건은 String보단 Enum으로 만드는게 좋을 것 같아요 ~

2024-08-31 15:00 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProductBySortedBy(String sortedBy, Pageable pageable) {
아 뭔가 여기가 질문주셨던 내용의 답인 것 같네요?
id가 offset이 되어야 할 것 같은데 왜 빼신걸까요 ?

2024-09-01 06:09 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +		Long nextCursorId = hasNext ? products.get(products.size() - 1).getId() : -1;
앗 슬랙에 다시 정리해서 댓글 남겼습니다!

2024-09-01 06:09 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +	private List<Product> getProductByCursorIdAndSortedBy(Long cursorId, String sortedBy, Pageable pageable) {
넵 알겠습니다!

2024-09-01 06:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +			.map(product -> {
앗 넵 수정하도록 했습니다.
저번에도 비슷한 피드백 주셨는데 피드백 항상 생각하면서 개발하겠습니다 !! 죄송함다

2024-09-06 14:41 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
이거 몇개 다시 보고 가면 좋을 것 같아서 리뷰 재요청 해놓을게요 ~

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/config/QueryDSLConfig.java
> +    public JPAQueryFactory jpaQueryFactory() {
메서드로 빈 생성하면 파라미터로 `EntityManager` 바로 받아줘도 될거같아요 ~

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        @RequestPart(name = "Images") List<MultipartFile> files) {
요거는 왜 이름이 대문자로 시작할까요 ?

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    private int pageNo; // 현재 페이지 넘버
요거 근데 api 문서는 혹시 어떻게 만드실 생각이실까요 ?

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    private int pageSize; // 페이지 사이즈
페이징같은 경우는 같은 서비스에선 공통적인 응답을 하는 경우가 많아요
PagingResponse 같은걸로 한번 감싸고 제네릭을 이용해보면 좋을 것 같아요 ~

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    public static ProductPagingResponse from(List<ProductFindResponse> productFindResponses, int pageNo, int pageSize,
뭔가 줄바꿈이 이랬다저랬다 하네요 ㅋㅋ 컨벤션이 어떻게먹은거지 ?

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryCustom.java
> +    Page<Product> findProductsWithCriteria(String keyword, int pageNo, int pageSize, OrderBy order);
요거 굳이 Page로 리턴할 필요 있나요 ?

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +        if (keyword != null && !keyword.isEmpty()) {
ifNotNull 이나 ifNotEmpty 같은 공통 메서드 하나 만들어두면 좋을 것 같아요 ~

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +            builder.and(product.productName.containsIgnoreCase(keyword))
contains 단점이 뭐가있을까요 ?

2024-09-06 14:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +    private OrderSpecifier<?> getOrderSpecifier(OrderBy sort) {
OrderBy 요거를 도메인 레이어에 넣어두고 enum에서 다 처리해도 될거같은데요 ?

2024-09-07 01:36 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        @RequestPart(name = "Images") List<MultipartFile> files) {
앗 실수입니다.. 수정하겠습니다..

2024-09-07 01:38 UTC, JIWON27 commented on src/main/java/com/example/readyauction/config/QueryDSLConfig.java
> +    public JPAQueryFactory jpaQueryFactory() {
아하 넵 수정하도록 하겠습니다!

2024-09-07 04:44 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryCustom.java
> +    Page<Product> findProductsWithCriteria(String keyword, int pageNo, int pageSize, OrderBy order);
Page에서 제공해주는 isLast, isFirst 등의 페이징 정보를 사용할려고 List가 아닌 Page로 반환해주도록 했습니다.

2024-09-07 04:45 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    private int pageSize; // 페이지 사이즈
앗 넵 수정하도록 하겠습니다.

2024-09-07 04:45 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    public static ProductPagingResponse from(List<ProductFindResponse> productFindResponses, int pageNo, int pageSize,
악 .. 확인해보게습니다.. ㅠㅠ

2024-09-07 04:47 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +        if (keyword != null && !keyword.isEmpty()) {
넵 공통 메서드 추가하겠습니다

2024-09-07 08:58 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +    private OrderSpecifier<?> getOrderSpecifier(OrderBy sort) {
오 다른 방향성 감사합니다.  훨씬 QueryDSL쪽이 깔끔해질 것 같습니다!

2024-09-07 09:06 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +            builder.and(product.productName.containsIgnoreCase(keyword))
contian는 DB로는 LIKE  %keyword%로 사용될텐데, 이는 인덱스를 사용하지 않기때문에 속도가 느려진다는 단점이 있을 것 같습니다.

2024-09-07 09:45 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/response/product/ProductPagingResponse.java
> +    private int pageNo; // 현재 페이지 넘버
엇 .. API 문서까지는 생각을 하고있지는 않았는데 생각하면서 개발하도록 하겠습니다

2024-09-08 16:37 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
머지하도록 할게요 ~

2024-09-08 16:37 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/OrderBy.java
> +    private final OrderSpecifierProvider orderSpecifierProvider;
요거 그냥 Function 써도 될거같아요 ?

2024-09-08 16:37 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/QueryUtils.java
> +public class QueryUtils {
말씀드린건 요거랑 좀 다른느낌이긴 한데 말로하기가 좀 어려워서 다음시간에 같이 한번 보시죠!

2024-09-08 16:37 UTC, merged