[#23] 좋아요 기능 구현 및 스프링 배치 적용
f-lab-edu/ready-auction pull request #26
Opened 2024-09-01 09:28 UTC by JIWON27

### 좋아요 기능 구현 및 스프링 배치 적용 (중간점검)
- BatchScheduler
- BatchConfig
- RedisConfig
- RedisLikeReader
- RedisLikeWriter
- ProductLikeService

2024-09-01 11:20 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
스레드로 말씀드린거 포함해서 수정 후 머지하면 좋을 것 같아요 ~

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/BatchScheduler.java
> +	@Scheduled(cron = "0 0 6 * * *") // 매일 오전 6시
배치 어플리케이션을 따로 만드실 예정이라면 `@Scheduled` 쓰는게 아니라 젠킨스같이 외부 툴을 이용해서 스케줄링을 할거라 여기서 안해줘도 될 것 같아요 ~

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +public class RedisLikeReader implements ItemReader<List<ProductLike>> {
요 Reader랑 Writer는 Job에 묶인거라 패키지를 같은 기능을 하는 애들끼리 묶어주면 좋을 것 같아요~

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +		Exception,
요거 줄바꿈이 좀 이상한거같아요 ?

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +	private List<ProductLike> productLikes = new ArrayList<>();
요건 멤버변수일 필요가 있을까요 ?

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +			Set<Long> usersIds = productLikeService.getUsersByProductId(productId);
요거 리턴값이 왜 Set일까요 ? 이유가 없으면 보통 쿼리 결과는 순회를 많이해서 List로 리턴하는게 좋을 것 같아요 ~

그리고 이거 그냥 stream 돌리면 아래 로직 굳이 필요 없을 것 같아요~

2024-09-01 11:20 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/config/BatchConfig.java
> +			.chunk(10, platformTransactionManager)
요거 청크사이즈 왜 이렇게 작게 잡으신걸까요 ?

2024-09-01 12:54 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/BatchScheduler.java
> +	@Scheduled(cron = "0 0 6 * * *") // 매일 오전 6시
아하 넵 알겠습니다!

2024-09-01 12:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +public class RedisLikeReader implements ItemReader<List<ProductLike>> {
앗 넵 수정하도록 하겠습니다!

2024-09-01 12:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +		Exception,
으악 죄송함다 ㅠㅠ 자꾸 탭이나 줄바꿈이 이상하네요...

2024-09-01 13:10 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +			Set<Long> usersIds = productLikeService.getUsersByProductId(productId);
아하 넵 수정하도록 하겠습니다~!

2024-09-02 01:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/RedisLikeReader.java
> +	private List<ProductLike> productLikes = new ArrayList<>();
앗 그렇네요,,, read() 메서드의 로컬변수로 수정하겠습니다.

2024-09-02 12:17 UTC, JIWON27 commented on src/main/java/com/example/readyauction/config/BatchConfig.java
> +			.chunk(10, platformTransactionManager)
앗 큰 의미는 없고 100으로 할려고했던게 10을 된거같습니당
100으로 수정하겠습니다.

2024-09-06 14:44 UTC, f-lab-moony requested changes
고생 많으셨습니다!
요것도 한번 다시 보면 좋을 것 같아요 ~

2024-09-06 14:44 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/BatchConfig.java
> +			.chunk(500, platformTransactionManager)
청크 사이즈는 상수로 빼면 좋을 것 같아요 ~

2024-09-06 14:44 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/RedisLikeReader.java
> +        ScanOptions scanOptions = ScanOptions.scanOptions().match("*").count(10).build();
여긴 사이즈 안바꿔줘도 되나요 ? 청크가 500인데 여기서 10개씩 읽으면 어떻게돼요 ?

2024-09-06 14:44 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/RedisLikeReader.java
> +            if (usersIds != null) {
List로 리턴되는데 null일수가 있나요 ?

2024-09-07 10:37 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/BatchConfig.java
> +			.chunk(500, platformTransactionManager)
앗 넵 알겠습니다

2024-09-07 10:38 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/RedisLikeReader.java
> +            if (usersIds != null) {
엇 그러네요... 수정하도록 하겠습니다 ㅜㅜ

2024-09-07 11:15 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/RedisLikeReader.java
> +            if (usersIds != null) {
아 Null일 수 없습니다.. 수정하도록 하겠습니다.
그리고 getUsersByProductId(...) 메서드 보니까 Set<Long> userIds = redisTemplate.opsForSet().members(productId);에서 membersrㅏ `@Nullable`어서 Set이 null일때 emptySet()으로 해주는 코드를 추가했습니다.

2024-09-07 11:42 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/RedisLikeReader.java
> +        ScanOptions scanOptions = ScanOptions.scanOptions().match("*").count(10).build();
아 사이즈 수정했습니다!
만약 청크사이즈가 동일하지 않으면 데이터 불일치 등의 문제가 발생할 수 있다고 생각합니바!!

2024-09-08 16:42 UTC, f-lab-moony approved these changes
고생 많으셨습니다
요것도 머지할게요 ~

2024-09-08 16:42 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductLikeService.java
> +            userIds = Collections.emptySet();
기본적으로 조건에 맞는 경우 어떤 값을 세팅해주고 밑에 리턴값에 반영되게 하는 것 보다
명시적으로 이런 경우 어떤 값이 리턴된다고 명확하게 드러내는게 좋을 것 같아요
물론 이런 방식이 필요한 경우도 있어서 무조건 그렇게 하자는건 아닌데, 지금같은경우는 null일 때 빈 리스트를 리턴한다는 명확한 목표가 있으니까 바로 리턴하는게 더 가독성이 좋을 것 같습니다 ~

2024-09-08 16:42 UTC, f-lab-moony commented
컨플릭났네요!
컨플릭 해결 후 머지 해주세요 ~

2024-09-09 10:29 UTC, merged