[#27] 좋아요 정렬 기능 추가
f-lab-edu/ready-auction pull request #28
Opened 2024-09-12 10:57 UTC by JIWON27

### 좋아요 정렬 기능 추가
- 정렬 기준에 좋아요 개수 추가
- 작성 예정

2024-09-14 12:45 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
>      public PagingResponse findAll(
요기 제네릭 타입도 추가해주면좋을 것 같아요 ~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        @RequestParam(value = "Status", required = false) Status status,
필드명이 대문자로 시작하고있어요 ~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        PagingResponse<ProductFindResponse> productPagingResponse = productFacade.findAll(keyword, status, pageNo,
이럴땐 굳이 변수로 한번 담을 필요 없을 것 같아요~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +        OrderSpecifier<?> orderSpecifier = order != null ? order.toOrderSpecifier() : product.id.desc();
OrderBy를 notnull로 취급하고 디폴트 값을 갖게 하는게 더 좋지 않을까요 ?

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +            return products;
이렇게 바로 리턴되는건 다 변수로 받을 필요 없어보여요 ~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +                .leftJoin(productLike).on(product.id.eq(productLike.productId))
요거혹시 N+1 쿼리 안날아가나요 ?

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +    private BooleanExpression containsKeyword(String keyword) {
요거 전에 만든 ifNotNull 사용하면 되지 않나요 ?

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +                case READY:
👍 
근데 요 내요들도 Status 안에 들어갈 수 있을 것 같아요 ~
추가로, Status 이름이 너무 범용적이라 경매상태 를 뜻하는 이름으로 바꿔주면 좋을 것 같아요 ~

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +        List<ProductImage> productImages = fileService.uploadImages(user, product, images);
요부분 ProductImageService로 들어가도 되지 않나 하는 생각이 드네요!

2024-09-14 12:45 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +    private void validateSaveRequest(ProductSaveRequest productSaveRequest, List<MultipartFile> images) {
👍

2024-09-16 07:10 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
>      public PagingResponse findAll(
앗 넵 추가하겠습니다.

2024-09-16 07:10 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        @RequestParam(value = "Status", required = false) Status status,
으악 수정하겠습니다..

2024-09-16 07:11 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        PagingResponse<ProductFindResponse> productPagingResponse = productFacade.findAll(keyword, status, pageNo,
넵 바로 return하도록 수정하겠습니다.

2024-09-16 07:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +        OrderSpecifier<?> orderSpecifier = order != null ? order.toOrderSpecifier() : product.id.desc();
넵 디폴트값을 가지도록 하는게 코드가 더 깔끔할 것 같습니다. 수정하도록 하겠습니다! 감사합니다

2024-09-16 07:13 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +            return products;
넵 수정하도록 하겠습니다

2024-09-16 07:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +    private BooleanExpression containsKeyword(String keyword) {
쿼리문 안에 바로 ifNotNull하는 것보다 containsKeyword()를 사용하는게 가독성이 더 좋다고 생각이 들어서
ifNotNull을 containsKeyword()에서 사용하도록 수정했습니다!

2024-09-16 07:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +                case READY:
넵 수정하도록 하겠습니다.

2024-09-16 07:25 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +        List<ProductImage> productImages = fileService.uploadImages(user, product, images);
이부분은 한번 고민해보도록 하겠습니다.!

2024-09-16 11:26 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +                .leftJoin(productLike).on(product.id.eq(productLike.productId))
N+1이 발생하는지 확인해보도록 하겠습니다.

+) 발생합니다.........
해결해보도록 하겠습니다.

2024-09-16 14:25 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/ProductRepositoryImpl.java
> +                .leftJoin(productLike).on(product.id.eq(productLike.productId))
넵 필요한 쿼리만 나갑니다!

2024-09-19 17:19 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~
이 PR은 여기서 머지 해두도록 할게요 ~

2024-09-19 17:19 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/ProductCondition.java
> +public enum ProductCondition {
👍

2024-09-19 17:19 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/product/ProductRepositoryImpl.java
> +    public BooleanExpression filterProductCondition(ProductCondition productCondition) {
이거 이렇게 now를 사용하면 테스트할때 좀 어려워질텐데 어떻게 해결해 볼 수 있을지 고민해보면 좋을 것 같네요 ~

2024-09-19 17:19 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/product/ProductRepositoryImpl.java
> +        if (productCondition != null) {
이것도 애초에 null이 아니라 디폴트값을 가질 수 있게 하면 좋을 것 같아요 ~

2024-09-19 17:19 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +    @Transactional
읽는데만 필요한 기능이라면 readOnly 속성을 true로 두는게 좋아요~ 왜 그럴지도 한번 찾아보면 더 좋겠네요!

2024-09-19 17:19 UTC, merged

2024-09-20 13:14 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/product/ProductRepositoryImpl.java
> +        if (productCondition != null) {
넵 디폴트값 가지도록 수정하겠습니다.

2024-09-20 13:15 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductFacade.java
> +    @Transactional
넵 readOnly 속성에 대해서 공부하겠습니다!

2024-09-20 13:16 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/product/ProductRepositoryImpl.java
> +    public BooleanExpression filterProductCondition(ProductCondition productCondition) {
넵 알겠습니다!  고민해보도록 하겠습니다