[#31] 경매 SSE 구독 및 가격 제안 기능 추가
f-lab-edu/ready-auction pull request #32
Opened 2024-09-18 04:39 UTC by JIWON27

### [#31] 경매 SSE 구독 및 가격 제안 기능 추가
- 경매 참여시 SSE 구독
- 가격 제안 기능 추가
- (중간 점검)

2024-09-19 17:35 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/auction/AuctionController.java
> +@RequestMapping("/api/v1/auction")
url에는 보통 도메인을 복수형으로 표현해줘요!

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/auction/AuctionController.java
> +    @GetMapping(value = "/{productId}/subscribe", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
이 컨트롤러가 다루는 도메인은 auction이고 패스도 `auction/` 이라서 당연히 여기엔 auctionId가 오게 될거라고 생각할거에요 다른 도메인의 아이디가 필요할땐 앞에 도메인 이름을 붙여주는게 좋아요 ~

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/auction/Auction.java
> +    private int bestPrice; // 유저가 부른 최고가
`최고가를 부른` 유저가 부른 최고가겠죠 ?

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/user/User.java
> +    public boolean equals(Object o) {
👍  그런데 엔티티의 경우 id를 유니크하게 가지고 있으니 밑에껄 전부 비교해야 할 필요가 있을지 생각해보면 좋을 것 같아요 ~

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/repository/auction/EmitterRepository.java
> +        Map<User, SseEmitter> emitters = emittersMaps.computeIfAbsent(productId, k -> new HashMap<>());
동시성 문제를 고민하셔서 위에는 Concurrent를 사용하셨는데 여기는 그냥 HashMap을 써도 되나요 ?

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        // 503 에러 방지를 위한 데이터 전송
👍

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +            // 동시성 제어가 필요한 부분?
어떤 부분에서 동시성 제어가 필요한지, 어떻게 제어할지도 혹시 생각 해 보셨을까요 ~?

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +    // 해당 경매에 참여한 User들에게 해당 경매 상품의 최고가가 갱신될때마다 SSE 알림.
👍

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +                .name("BEST PRICE UPDATE") // 이벤트의 이름을 "sse"로 지정
주석이랑 동작이 좀 다른 것 같군요 ?

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        // 경매가 끝나기 전까지 계속 최고가 알람을 줘야해서 경매 종료일 - 요청 시간 = SSE TimeOut
요거 굳이 이렇게 expire를 설정할 필요 있을까요 ? 그냥 경매 끝나는 액션 왔을때 해당 경매의 emitter 찾아서 종료시켜버리면 되는거 아닌가 싶어서요!

2024-09-19 17:35 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        // [나중에 추가 예정] 사용자가 "최고가 알람 끄기" 선택하면 delete
알람은 서버에서 꺼야하는건가 하는 생각이 드네요 ?

2024-09-20 13:16 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/auction/AuctionController.java
> +@RequestMapping("/api/v1/auction")
앗 넵 수정하겠습니다!

2024-09-20 13:17 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/auction/AuctionController.java
> +    @GetMapping(value = "/{productId}/subscribe", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
아하 넵! product 추가하도록 하겠습니다

2024-09-20 13:18 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/auction/Auction.java
> +    private int bestPrice; // 유저가 부른 최고가
넵 맞습니다! 주석이 약간 헷갈리게 되어있네용..

2024-09-20 13:47 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/user/User.java
> +    public boolean equals(Object o) {
엇 말씀하신것처럼 id는 user 엔티티마다 다 다르기때문에 전부 비교할필요 없이 id만 비교해도 될 것 같습니다.
수정하도록 하겠습니다!

2024-09-20 13:59 UTC, JIWON27 commented on src/main/java/com/example/readyauction/repository/auction/EmitterRepository.java
> +        Map<User, SseEmitter> emitters = emittersMaps.computeIfAbsent(productId, k -> new HashMap<>());
외부 Map을 ConcurrentHashMap을 사용해서 내부는 HasnMap을 사용해도 되겠다라고 생각을 했었는데, 내부맵도 동시에 put이나 remove와 같은 작업이 이루어질 수 있겠다는 생각이 들어서 내부도 동일하게  ConcurrentHashMap으로 수정하겠습니다!

2024-09-20 14:04 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +            // 동시성 제어가 필요한 부분?
두 사용자가 동시에 tenderPrice 메서드를 호출하고, 동일한 productId에 대해 입찰하는 경우에서 동시성 문제가 발생할 수 있다고 생각합니다., 
만약 첫 번째 사용자가 조회한 최고가가 1000원이고, 두 번째 사용자가 조회한 최고가도 1000원이라면, 둘 다 동시에 1000원 이상의 가격을 제안을 하겠다고 가정하면, 첫 번째 사용자가 1500원을 제안해서 성공적으로 최고가를 업데이트하고, 두 번째 사용자가 그 후에 최고가를 1200원으로 업데이트하는 상황이 발생할 수 있다고 생각이 듭니다.

방법은 현재 찾아보고 있습니다.

2024-09-20 14:07 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +                .name("BEST PRICE UPDATE") // 이벤트의 이름을 "sse"로 지정
앗 수정하겠습니다 ㅎ...

2024-09-20 14:11 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        // [나중에 추가 예정] 사용자가 "최고가 알람 끄기" 선택하면 delete
요 부분은 추후에 고민하고 있는 기능입니다.
단순하게 생각해서 예를들어 사용자가 설정에서 최고가 알람 받기 기능을 끄면 emitter를 삭제하도록 할려고했는데 이 부분은 조금 더 고민해보겠습니다!

2024-10-10 12:20 UTC, f-lab-moony approved these changes
고생 많으셨습니다! 요건 바로 머지 할게요 ~

2024-10-10 12:20 UTC, merged