[#33] 경매 Redis 저장/삭제 기능 추가
f-lab-edu/ready-auction pull request #34
Opened 2024-09-19 15:46 UTC by JIWON27

### 경매 Redis 저장/삭제 기능 추가
- 상품 조회 시 request 시간과 상품 startDate를 비교하여 시작일을 넘었다면 Redis에 저장하고 TTL은 closeDate기간으로 계산.

2024-10-10 12:26 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~ 피드백 확인 부탁드려요!

2024-10-10 12:26 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        LocalDateTime request = LocalDateTime.now();
request라는 이름이 좀 어색한 것 같아요 ~ requestTime 이나 좀 더 명시적으로 쓰일 이름으로 바꿔주면 좋을 것 같아요

2024-10-10 12:26 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        ProductFindResponse productFindResponse = productFacade.findById(id, request);
이런건 인라인으로 리턴해도 되지 않을까요 ?

2024-10-10 12:26 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +    public void updateProductCondition(ProductCondition productCondition) {
엔티티 변경시에는 누가 변경했는지도 같이 받아서 바꿔주면 좋을 것 같아요!

2024-10-10 12:26 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +            product.updateProductCondition(ProductCondition.ACTIVE);
아 요렇게 쓰이는거군요 ? 이거 상태를 엔티티가 직접 가지고 있을 이유가 있을까요 ? 이러면 조회 요청이 트리거가 돼서 상태가 변경되는건데 상태를 가지는게 아니라 응답에만 포함되어도 될 것 같아요 ~ 추가로, 상태값 관리하는건 별도의 배치나 스케줄러가 있어야 하지 않을까 싶은데 어떻게 생각하실까요 ?

2024-10-11 16:51 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        LocalDateTime request = LocalDateTime.now();
넵 알겠습니다!

2024-10-11 16:51 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/product/ProductApiController.java
> +        ProductFindResponse productFindResponse = productFacade.findById(id, request);
넵!!

2024-10-11 16:52 UTC, JIWON27 commented on src/main/java/com/example/readyauction/domain/product/Product.java
> +    public void updateProductCondition(ProductCondition productCondition) {
아항 넵 추가하도록 하겠습니다

2024-10-11 17:35 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/product/ProductService.java
> +            product.updateProductCondition(ProductCondition.ACTIVE);
음 저도 상태쪽을 솔직히 requestTime을 받아서 필터링하는건 별로라고 생각하고있었는데 피드백 감사합니다!
저도 상태같은 경우는 startDate와 clsoeDate가 있으니까 배치나 스케줄러를 사용해도 좋을 것 같습니다!

2024-10-16 08:31 UTC, f-lab-moony requested changes
고생 많으셨습니다!
피드백 확인 부탁드려요 ~

2024-10-16 08:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductConditionUpdate.java
> +    public Product process(Product product) throws Exception {
요거 그냥 Writer에서 하고 Processor 빼도 될거같아요 ?

2024-10-16 08:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +    private static final int PAGE_SIZE = 500;  // 한번에 읽을 데이터 개수 (청크 사이즈)
요거 CHUNK_SIZE를 같이 사용하는게 어떨까요 ?

2024-10-16 08:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +        Exception,
예외 목록이 약간 읽기 어렵게 줄바꿈이 된 것 같아요

2024-10-16 08:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +            currentPage = 0;
요거는 혹시 무슨 의도인가요 ?

2024-10-16 08:31 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +        Pageable pageable = PageRequest.of(currentPage, PAGE_SIZE);
전체를 다 읽는거라 데이터가 많아지면 점점 느려질 것 같아요, more 방식으로 읽도록 변경하는게 어떨까요 ?

2024-10-17 10:46 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +            currentPage = 0;
엇 이게 DB에서 더이상 읽어올게없으면 다시 처음부터 읽을 수 있도록 pageNo를 0으로 하는 코드였습니다!

2024-10-17 10:49 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +        Pageable pageable = PageRequest.of(currentPage, PAGE_SIZE);
아 그렇네요!! more 방식으로 수정하도록 하겠습니다!

2024-10-17 10:50 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductConditionUpdate.java
> +    public Product process(Product product) throws Exception {
넵 수정하도록 하겠습니다!

2024-10-17 10:50 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +    private static final int PAGE_SIZE = 500;  // 한번에 읽을 데이터 개수 (청크 사이즈)
아하 넵!!

2024-10-17 10:51 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductReader.java
> +        Exception,
요게 저두 불편한데,, 줄바꿈을 제가 바꿔두 save 하면 저런식으로 줄바꿈이 되더라구용,,,🥲

2024-10-18 08:39 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~ 요거 머지 할게요!

2024-10-18 08:39 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/BatchConfig.java
> +    @Value("${ready.auction.spring.batch.chunkSize}")
요거 근데 아마 잡마다 청크사이즈가 달라서 이렇게 퉁치긴 좀 어렵긴 할텐데 나중에 기회되면 바꿔보시죠 ~
저는 JobConfig가 최상단이라 거기 있는 애들 public static으로 같이 쓰고 있어요

2024-10-18 08:39 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/batch/job/ProductConditionWriter.java
> +        // 경매 상태 업데이트
요 주석들 굳이 없어도 읽는데 문제 없을 것 같아요 ~
주석은 최대한 일반적이지 않은 코드를 위한 히스토리 혹은 참고할 문서가 있는 경우에만 남겨주세요

2024-10-18 08:39 UTC, merged

2024-10-18 08:56 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/job/ProductConditionWriter.java
> +        // 경매 상태 업데이트
넵 알겠습니다!

2024-10-18 08:57 UTC, JIWON27 commented on src/main/java/com/example/readyauction/batch/BatchConfig.java
> +    @Value("${ready.auction.spring.batch.chunkSize}")
아하 넵 ! 저도 해보다가 애매하면 JobConfig에 사이즈를 두고 사용하도록 하겠습니다