[#33] 가격 제안(입찰) 동시성 이슈 해결
f-lab-edu/ready-auction pull request #36
Opened 2024-10-13 07:54 UTC by JIWON27

### 가격 제안(입찰) 동시성 이슈 해결
- Redis 분산 락을 활용하여 가격 제안(입찰) 동시성 이슈 해결

2024-10-14 09:46 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +            if (!lock.tryLock(5, 10, TimeUnit.SECONDS)) {
여기에 lock wait time이랑 lease time은 코드 실행속도 측정해보면서 적당히 넉넉하게 정해야할것같아서 측정해보고 수정할 예정입니다.

2024-10-16 08:38 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-10-16 08:38 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/apiException/ApiExceptionController.java
> +    public ErrorResponse redisLockAcquisitionException(RedisLockAcquisitionException e) {
ExceptionHandler에선 Http Status 지정해주는게 좋을 것 같아요 ~ ResponseEntity로!

2024-10-16 08:38 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +    public void subscribeCancel(CustomUserDetails user, Long productId) {
이거 유효성검사가 있어야 할 것 같아요. 현재 자신이 최고가 입찰이라면 종료를 못한다던가 같은 ?

2024-10-16 08:38 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +        Map<User, SseEmitter> sseEmitterMap = emitterRepository.get(productId);
키를 좀 바꿔야 할 것 같아요. 일단 객체를 키로 쓰는건 위험한 행위라 지양하는게 좋구요. 유저가 여러 경매에 동시에 참여중이라면 유니크하지 못할 것 같아요. product+userId 를 키로 갖거나, product 하위에 user별 emitter를 가진 구조가 나와야 할 것 같습니다

2024-10-16 08:38 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        RLock lock = redissonClient.getLock("lock:" + productId);
요게 레디스 락이군요 ?

2024-10-16 08:38 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        RLock lock = redissonClient.getLock("lock:" + productId);
락 획득하는 부분은 try로 안들어가도 되나요 ?

2024-10-17 10:16 UTC, JIWON27 commented on src/main/java/com/example/readyauction/controller/apiException/ApiExceptionController.java
> +    public ErrorResponse redisLockAcquisitionException(RedisLockAcquisitionException e) {
아하 넵 !!

2024-10-17 10:17 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +    public void subscribeCancel(CustomUserDetails user, Long productId) {
넵 유효성 검사 고민하고 추가하겠습니다!

2024-10-17 10:21 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        RLock lock = redissonClient.getLock("lock:" + productId);
Lock 획득은 밑에 tryLock에서 확인합니다! 그래서 tryLock하는 부분을 try로 들어가도록 했습니다.

2024-10-17 10:22 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +        Map<User, SseEmitter> sseEmitterMap = emitterRepository.get(productId);
아하 넵 키 수정하도록 하겠습니다! 감사합니다

2024-10-18 08:39 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/controller/apiException/ApiExceptionController.java
> +    public ErrorResponse redisLockAcquisitionException(RedisLockAcquisitionException e) {
아 위에 어노테이션이 있었네요 저거 못봤어요 ㅋㅋ

2024-10-18 08:40 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +    public void subscribeCancel(CustomUserDetails user, Long productId) {
구독 해제 == 입찰 포기가 아닌건가요 ? 그냥 알림 그만받기 같은거에요 ?

2024-10-18 08:41 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +        Map<User, SseEmitter> sseEmitterMap = emitterRepository.get(productId);
아아 이게 한번 감싸진 대상이군요 이해했습니다 ~

2024-10-18 08:42 UTC, f-lab-moony commented on src/main/java/com/example/readyauction/service/auction/AuctionService.java
> +        RLock lock = redissonClient.getLock("lock:" + productId);
getLock은 실제 락 획득이 아니라 락 객체를 가져오는건가보군요 넵 알겠습니다 ~

2024-10-18 08:42 UTC, f-lab-moony approved these changes
코멘트 확인했습니다 ~
별도로 남겨둔것도 있긴 한데 확인 부탁드려요
요건 머지 하도록 할게요 ~

2024-10-18 08:42 UTC, merged

2024-10-18 08:52 UTC, JIWON27 commented on src/main/java/com/example/readyauction/service/auction/HighestBidSseNotificationService.java
> +    public void subscribeCancel(CustomUserDetails user, Long productId) {
네 그냥 최고가 알림 그만 받기 입니다!