[#37] 경매 상품 실시간 가격 변동 처리
f-lab-edu/ready-auction pull request #43
Opened 2024-11-09 13:41 UTC by JIWON27

### 경매 상품 최고가 변경시 이벤트 발생 및 SSE 알림
- Kafka 사용
- SSE 사용

2024-11-10 13:56 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-11-10 13:56 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/config/WebSecurityConfig.java
> +                .requestMatchers(new AntPathRequestMatcher("/auction/kafkaEvent/subscribe")).permitAll()
요거 근데 kafkaEvent라는건 알려줄 필요 없는 정보같아요 ~

2024-11-10 13:56 UTC, f-lab-moony commented on module-domain/src/main/java/com/example/moduledomain/repository/kafka/KafkaEmitterRepository.java
> +public class KafkaEmitterRepository {
요거때문에 모듈이 하나 분리되어있는 것 같은데 맞나요 ?
근데 이거 워커에서만 갖고 있으면 되는거 아닌가요 이제 ?

2024-11-10 13:56 UTC, f-lab-moony commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaEmitterService.java
> +                    .name("경매 상품 최고가 변경")
요거 이벤트 발행은 다른 기능에서도 쓸 수 있으니 name도 받게 해주는게 어떨까요 ?

2024-11-10 13:56 UTC, f-lab-moony commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaEmitterService.java
> +public class KafkaEmitterService {
여기 Kafka가 붙을 필요가 없을 것 같아요 ~

2024-11-10 13:56 UTC, f-lab-moony commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaListenerService.java
> +            SseEmitter adminEmitter = kafkaEmitterService.getAdminEmitter();
이거 어차피 서비스 내에서 만들 수 있는거면 굳이 여기서 안만들어줘도 되지 않나요 ?

2024-11-11 01:58 UTC, JIWON27 commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaEmitterService.java
> +public class KafkaEmitterService {
넵 알겠습니다!

2024-11-11 01:58 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/config/WebSecurityConfig.java
> +                .requestMatchers(new AntPathRequestMatcher("/auction/kafkaEvent/subscribe")).permitAll()
넵 알겠습니다!! 
삭제하도록 하겠습니당

2024-11-11 02:00 UTC, JIWON27 commented on module-domain/src/main/java/com/example/moduledomain/repository/kafka/KafkaEmitterRepository.java
> +public class KafkaEmitterRepository {
넵 워커 모듈로 가져오도록 하겠습니다!

2024-11-11 02:02 UTC, JIWON27 commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaEmitterService.java
> +                    .name("경매 상품 최고가 변경")
넵! name도 받을 수 있도록 하겠습니다

2024-11-11 02:22 UTC, JIWON27 commented on module-worker/src/main/java/com/example/moduleworker/Service/KafkaListenerService.java
> +            SseEmitter adminEmitter = kafkaEmitterService.getAdminEmitter();
여러 방법 중 ObjectMapper를 사용해서 역직렬화한 것인데 ObjectMapper 사용안하도록 한번 해보겠습니다!

2024-11-20 15:37 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요건 더 볼건 없을거같아서 머지 하도록 할게요 ~

2024-11-20 15:37 UTC, merged