[#46] 경매 상품 결제(포인트) 기능 추가
f-lab-edu/ready-auction pull request #47
Opened 2024-11-23 05:41 UTC by JIWON27

### 경매 상품 결제(포인트) 기능 추가

2024-11-24 14:40 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 ~

2024-11-24 14:40 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/controller/point/PointController.java
> +    @PostMapping("/deduct")
요거는 말씀하신거처럼 배치에서 낙찰자 판단하고 거기서 차감하는게 맞지 않을까 싶네요!

2024-11-24 14:40 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    private static void validateDeductPoint(PointAmount pointAmount, User user, Point point) {
배치에서 차감을 한다고 할 때, 이 사람이 다른 경매도 참여해서 실제 결제시에는 포인트가 부족할 수도 있겠네요!
그거에 대한 생각도 해보면 좋을 것 같아요!

2024-11-24 14:40 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    public int chargePoint(CustomUserDetails userDetails, PointAmount pointAmount) {
트랜잭션이 안 걸린 것 같아요 ~

2024-11-25 07:38 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/controller/point/PointController.java
> +    @PostMapping("/deduct")
앗 그러네요!! 필요없는 API네용.. 삭제하겠습니다!

2024-11-25 07:45 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    private static void validateDeductPoint(PointAmount pointAmount, User user, Point point) {
아 그런 문제점이 있을 수 있군요!!! 고민해보도록 하겠습니다! 
감사합니다.

2024-11-25 07:46 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    public int chargePoint(CustomUserDetails userDetails, PointAmount pointAmount) {
앗 자꾸... ㅠㅠ
추가하도록 하겠습니다!

2024-11-25 07:48 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    private static void validateDeductPoint(PointAmount pointAmount, User user, Point point) {
아니면 이런 방법은 어떨까요?!
경매 입찰 시도할때 가격만큼 포인트에서 차감을 시킨 다음에 경매에 실패하면 다시 포인트 롤백해주는건 어떤지 궁금합니다!

2024-11-25 08:21 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        pointService.rollbackPoint(userIdAndCurrentPrice.getFirst(), userIdAndCurrentPrice.getSecond().intValue());
redis 최고가 정보 변경 전에 포인트를 롤백해주도록 추가했습니다.
이러면 실제 결제 시 포인트 부족 문제를 해결할 수 있을 것 같습니다!
혹시 제가 놓치고 있는 부분이 있을까요?!

2024-11-25 08:23 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        pointService.deductPoint(user, pointAmount);
경매 입찰이 가능한지 검증하는 메서드쪽에 포인트 차감하는 코드를 추가했습니다

2024-12-01 08:42 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    private static void validateDeductPoint(PointAmount pointAmount, User user, Point point) {
요건 저번 멘토링때 얘기 나눴던 것 같네요! 전 좋은 방법 같습니다!

2024-12-01 08:43 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        pointService.rollbackPoint(userIdAndCurrentPrice.getFirst(), userIdAndCurrentPrice.getSecond().intValue());
지금은 괜찮아보여요!

2024-12-01 10:05 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/point/PointService.java
> +    private static void validateDeductPoint(PointAmount pointAmount, User user, Point point) {
넵 감사합니다!

2024-12-01 10:05 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        pointService.rollbackPoint(userIdAndCurrentPrice.getFirst(), userIdAndCurrentPrice.getSecond().intValue());
넵 감사합니다~!

2024-12-01 10:31 UTC, f-lab-moony approved these changes
고생 많으셨습니다 ~ 이번 PR은 머지하도록 할게요!

2024-12-01 10:31 UTC, merged