[#38] 경매 종료시 낙찰 정보 업데이트
f-lab-edu/ready-auction pull request #48
Opened 2024-11-24 07:10 UTC by JIWON27

### 경매 종료시 낙찰 정보 업데이트
-  스프링 배치에서 경매 상품 상태가 종료로 변할 시 낙찰 DB에 업데이트

2024-11-24 14:33 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 후 수정 부탁드려요 ~

2024-11-24 14:33 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +                String.valueOf(productId)); // productId : (userId, bestPrice)
요거 주석 굳이 필요할까 싶긴 한데, 이런 주석이 필요하시더라도 매 라인마다 달기보단 javadoc으로 메서드나 필요한 라인 위에 합쳐서 달아주는게 좋을 것 같아요 ~ 이렇게 라인별로 달면 코드 활용도 힘들고 가독성에도 별로 좋지 않아서요

2024-11-24 14:33 UTC, f-lab-moony commented on module-batch/src/main/java/com/example/modulebatch/batch/job/ProductConditionWriter.java
> +                if (auctionUserInfoByProductId.isPresent()) {
있을경우 동작을 정의하는거라면 ifPresent를 이용해보면 어떨까요 ?

2024-11-24 14:33 UTC, f-lab-moony commented on module-batch/src/main/java/com/example/modulebatch/batch/job/ProductConditionWriter.java
> +                // Optional로 반환된 값 처리
요건 좀 다른얘기일 수 있는데, 이 분기 처리하는게 위에 지금 now로 계산을 하고 있는데요, 조금 생각해보면 그 아래에 바로 나오는 경매 상태 코드가 그 분기에 따라 달라지고 있어요.

그럼, ProductCondition에서 now를 통해 컨디션 반환해주는 로직만 있으면 분기가 필요 없어져서 변화에 더 유연한 구조를 가질 수 있을 것 같아요!

2024-11-25 08:25 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +                String.valueOf(productId)); // productId : (userId, bestPrice)
앗 넵!! 다른 곳에도 주석이 달려있는데 주석부분은 한번 싹 정리하도록 하겠습니다!
감사합니다

2024-11-25 08:55 UTC, JIWON27 commented on module-batch/src/main/java/com/example/modulebatch/batch/job/ProductConditionWriter.java
> +                if (auctionUserInfoByProductId.isPresent()) {
앗 넵 알겠습니다!
감사합니다

2024-11-25 09:10 UTC, JIWON27 commented on module-batch/src/main/java/com/example/modulebatch/batch/job/ProductConditionWriter.java
> +                // Optional로 반환된 값 처리
아하 생각 못했던 부분입니다!
그럼 훨씬더 가독성도 좋아질 것 같습니다!
수정하도록 하겠습니다~!

2024-12-01 10:36 UTC, f-lab-moony approved these changes
고생 많으셨습니다!
요것도 바로 머지 하도록 할게요 ~

2024-12-01 10:36 UTC, f-lab-moony commented on module-domain/src/main/java/com/example/moduledomain/domain/product/ProductCondition.java
> +        if (now.isBefore(product.getStartDate())) {
지금도 좋긴 한데, 요거보다는 각 enum 값이 조건을 가지고 있으면 더 좋을 것 같아요!

2024-12-01 10:36 UTC, merged

2024-12-01 10:43 UTC, JIWON27 commented on module-domain/src/main/java/com/example/moduledomain/domain/product/ProductCondition.java
> +        if (now.isBefore(product.getStartDate())) {
아하 넵 수정하도록 하겠습니다!