[#51] 상품 추천 기능 개발(2) - 상품 추천 알고리즘 개발
f-lab-edu/ready-auction pull request #52
Opened 2024-12-07 09:38 UTC by JIWON27

### 상품 추천 기능 개발(2)
- 상품 추천 알고리즘 개발

2024-12-15 08:57 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요 ~

2024-12-15 08:57 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +                .map(id -> findById(id))
이렇게하면 추천받은 개수만큼 select 쿼리가 날아갈 것 같아요, id를 따로 빼서 한번에 조회하도록 하는게 어떨까요 ?

2024-12-15 08:57 UTC, f-lab-moony commented on module-domain/src/main/java/com/example/moduledomain/repository/bidLogging/BidLoggingRepositoryImpl.java
> +        for (AgeRange range : ageRanges) {
나이대 빼고 검색한다음에 어플리케이션에서 그룹을 만드는 건 어떨까요 ?

2024-12-15 08:57 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +public class ProductRecommendationService {
요거 의존성 추가해서 직접 서비스 호출해서 쓰고 있는 것 같은데, 말씀드렸던 방법은 api 서버 따로 띄워서 api 호출로 가져오는거였어요!

2024-12-15 08:57 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    private static final List<String> GENDERS = Arrays.asList("남성", "여성");
문자열 말고 enum으로 관리해도 되지 않을까요 ?

2024-12-15 08:57 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        String age = String.valueOf((user.getAge() / 10) * 10);
요건 왜 이렇게 계산하신걸까요 ?

2024-12-15 08:57 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    @Scheduled(cron = "0 27 3 * * THU")
요거 무슨 기준으로 잡힌 시간일까요 ?

2024-12-15 11:54 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    private static final List<String> GENDERS = Arrays.asList("남성", "여성");
넵 ! enum으로 관리하도록 수정하겠습니다

2024-12-15 11:56 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +                .map(id -> findById(id))
아하 넵 피드백주신대로 수정하겠습니다!

2024-12-15 12:00 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +public class ProductRecommendationService {
앗 넵 제가 잘못 이해했나봅니다!!
추천 상품만 반환해주는 API 서버로 수정하도록 하겠습니다

2024-12-15 12:02 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        String age = String.valueOf((user.getAge() / 10) * 10);
사용자이 나이가 20대인지 30대인지를 알려고 계산했습니다!
24살 이라고 했을  24 / 10 == 2 , 2 * 10해서 20으로 계산할려고 했습니다!

2024-12-15 12:03 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    @Scheduled(cron = "0 27 3 * * THU")
앗 시간은 아직 기준을 정하지는 않았습니다! 
테스트할려고 했던 시간으로 올라갔습니다 ㅎㅎ..

2024-12-15 12:03 UTC, JIWON27 commented on module-domain/src/main/java/com/example/moduledomain/repository/bidLogging/BidLoggingRepositoryImpl.java
> +        for (AgeRange range : ageRanges) {
카테고리만 쿼리로 조회를 하고 어플리케이션에서 나이대별 그룹을 만들라는 말씀이신가요?!

2024-12-22 10:08 UTC, f-lab-moony requested changes
고생 많으셨습니다 ~
피드백 확인 부탁드려요!

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/controller/product/ProductApiController.java
> +        @RequestParam(value = "keyword", required = false) String keyword,
파라미터가 꽤 많은데 그냥 RequestBody로 받는게 낫지 않을까요 ?
api는 종종 curl 요청으로도 많이 해서, 그런부분도 신경써주면 좋을 것 같아요, 저는 개인적으로 2개 넘어가면 그냥 body로 받는데요, 그러려면 POST 요청이 되어야 해서 애매하실수도 있는데, 조회요청은 POST요청으로도 하는 경우가 많으니 괜찮아요

지금은 그런 형식은 아니긴 한데, 예를들어 product Id 목록을 받는 경우, 파라미터로 받으면 HTTP 요청의 url max size에 걸려서 예기치 못한 갯수 제한에 걸릴 수가 있는데, 이런식으로 요청 값이 많아질 때 POST로 조회 요청을 설계하는 경우가 꽤 있어요

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        return ((double)(nextPrice - previousPrice) / previousPrice) * 100;
이런건 바로 위랑 값만 다르지 로직이 같아서 메서드로 한번 뽑아주시면 좋을 것 같아요 ~

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +@Profile("dev")
이건 왜 걸어두신걸까요 ?

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +    public PagingResponse<ProductFindResponse> findAll(CustomUserDetails customUserDetails, String keyword,
findAll은 전체를 찾아오는거라 동작이랑 조금 안 맞는 것 같아요!

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +    @Value("${ready.auction.recommendation.server.base.url}")
이건 위치가 왜 여기있을까요 ?

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +        RestClient client = RestClient.create();
딱히 문제가 있는 건 아닌데, FeignClient도 한번 써보시면 좋을 것 같아요 ~ 인터페이스 기반으로 api 요청을 관리할 수 있어서 쓰기 편해요

2024-12-22 10:08 UTC, f-lab-moony commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +        RestClient client = RestClient.create();
별도로, 여기서도 Client는 따로 클래스를 만들어서 관리하시는게 좋을 것 같아요 ~

2024-12-22 10:08 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    private String getAgeGroup(int age) {
이거 enum으로 정의해보는건 어떨까요 ?

2024-12-22 10:08 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        for (Gender genderType : GENDERS) {
enum을 만들어둔 상태여서 Gender.values() 를 이용해보면 어떨까요 ?

2024-12-22 10:08 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        initializeRecommendationProductStore();
요거 어차피 한번만 수행되길 원하는 녀석이라 static 블럭에서 해도 좋을 것 같아요

2024-12-22 10:08 UTC, f-lab-moony commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        saveInRecommendationProductStore(Gender.MALE, getTop2CategoriesByAgeGroup(Gender.MALE));
근데 여기서 어차피 넣어주는데 initializeRecommendationProductStore 이게 따로 필요 할까요 ?

2024-12-22 18:16 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/controller/product/ProductApiController.java
> +        @RequestParam(value = "keyword", required = false) String keyword,
파라미터가 꽤 많다고는 생각이 들었는데 POST 요청으로도 하기도 하는군요...첨 알았습니다!
이 부분은 정렬/필터 고도화쪽을 진행할때 코드 수정하도록 하겠습니다!!

2024-12-22 18:16 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/auction/AuctionService.java
> +        return ((double)(nextPrice - previousPrice) / previousPrice) * 100;
넵 알겠습니다!

2024-12-22 18:16 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +@Profile("dev")
dev파일에 추천서버 IP/PORT를 작성해놔서 Profile('dev') 추가한거였습니다!
근데 Feign 사용하도록 하면서 필요없어져서 삭제하겠씁니다!

2024-12-22 18:17 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +    public PagingResponse<ProductFindResponse> findAll(CustomUserDetails customUserDetails, String keyword,
이름 수정하도록 하겠습니다~!

2024-12-22 18:18 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +    @Value("${ready.auction.recommendation.server.base.url}")
엇 위치를 이상한데다 했군요...죄송합니다..
근데 이것두 Feign 사용하도록 하면서 필요없어져서 삭제하겠씁니다!

2024-12-22 18:18 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +        RestClient client = RestClient.create();
아하 넵 알겠습니다!! 찾아보고 적용하도록 하겠습니다!

2024-12-22 18:18 UTC, JIWON27 commented on module-api/src/main/java/com/example/moduleapi/service/product/ProductFacade.java
> +        RestClient client = RestClient.create();
넵 알겠습니다~!!

2024-12-22 18:18 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +    private String getAgeGroup(int age) {
넵 enum으로 처리하도록 수정하겠습니다!

2024-12-22 18:18 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        for (Gender genderType : GENDERS) {
이 부분은 코드 수정하면서 불필요해서 삭제했습니다!

2024-12-22 18:18 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        initializeRecommendationProductStore();
이 부분도 마찬가디로 코드 수정하면서 불필요해서 삭제했습니다!

2024-12-22 18:18 UTC, JIWON27 commented on module-recommendation/src/main/java/com/example/modulerecommendation/service/ProductRecommendationService.java
> +        saveInRecommendationProductStore(Gender.MALE, getTop2CategoriesByAgeGroup(Gender.MALE));
initializeRecommendationProductStore를 한 이유는 Map에 값을 넣어줄려고할때 null이 뜨지 않도록 초기화 해주는 목적이었는데 computeIfAbsent를 사용하는 방식으로 수정해서 삭제했습니다!

2025-01-03 14:55 UTC, merged